package(default_visibility = ["//visibility:public"])

cc_library(
    name = "sim_32u4",
    hdrs = [
        "iom32u4.h",
        "sim_32u4.h",
        "sim_core_declare.h",
    ],
    deps = [
        "@third_party//:simavr",
	"//src/native:constants",
    ],
)
