package(default_visibility = ["//visibility:public"])

cc_library(
    name = "simavr_core",
    hdrs = [
        "sim_core_declare.h",
        "sim_megax.h",
    ],
    deps = ["@third_party//:simavr"],
)
