load(
    "@bazel_tools//tools/build_defs/repo:git.bzl",
    "git_repository",
)

# custom AVR-specific rules
git_repository(
    name = "avr-bazel",
    commit = "b9af17ea27c463d2104d4240a7b3b44d55b29b23",
    remote = "https://github.com/taylorconor/avr-bazel",
)

load(
    "@avr-bazel//:avr.bzl",
    "avr_tools_repository",
)
avr_tools_repository()

# google test and google mock
git_repository(
    name = "gtest",
    commit = "703bd9caab50b139428cea1aaff9974ebee5742e",
    remote = "https://github.com/google/googletest",
)

# a local repo representing the third party library locations (e.g. for simavr).
# TODO: this is platform-specific and needs to be generalised.
new_local_repository(
    name = "third_party",
    path = "/usr/local/",
#    path = select({
#        "//conditions:default": "/usr/local/",
#    }),
    workspace_file = "third_party/WORKSPACE.third_party",
    build_file = "third_party/BUILD.third_party",
)