# custom AVR-specific rules
load(
    "@bazel_tools//tools/build_defs/repo:git.bzl",
    "git_repository",
)

# custom AVR-specific rules
git_repository(
    name = "avr-bazel",
    commit = "d898f734aa2803de14c10d4cbddc278d7a59b540",
    remote = "https://github.com/taylorconor/avr-bazel",
)

load(
    "@avr-bazel//:avr.bzl",
    "avr_tools_repository",
)
avr_tools_repository()

# google test and google mock
git_repository(
    name = "gtest",
    commit = "703bd9caab50b139428cea1aaff9974ebee5742e",
    remote = "https://github.com/google/googletest",
)

# a local repo representing the third party library locations (e.g. for simavr).
# TODO: this is platform-specific and needs to be generalised.
new_local_repository(
    name = "third_party",
    path = "/usr/local/",
    build_file = "third_party/BUILD.third_party",
)