load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# custom AVR-specific rules
git_repository(
    name = "avr-bazel",
    commit = "b7f50ee9d2835d7ce42990dd2732af89cbcb0915",
    remote = "https://github.com/taylorconor/avr-bazel",
    shallow_since = "1590245556 +0200",
)

load("@avr-bazel//:avr.bzl", "avr_tools_repository")

avr_tools_repository()

# google test and google mock.
git_repository(
    name = "gtest",
    commit = "703bd9caab50b139428cea1aaff9974ebee5742e",
    remote = "https://github.com/google/googletest",
    shallow_since = "1570114335 -0400",
)

# google abseil library.
git_repository(
    name = "abseil",
    commit = "e1d388e7e74803050423d035e4374131b9b57919",
    remote = "https://github.com/abseil/abseil-cpp",
    shallow_since = "1618937714 -0400",
)

# rapidcheck property-based testing library.
http_archive(
    name = "emil-e",
    build_file = "//third_party:BUILD.third_party",
    strip_prefix = "rapidcheck-master",
    urls = ["https://github.com/emil-e/rapidcheck/archive/refs/heads/master.zip"],
)

http_archive(
    name = "nlohmann",
    build_file = "//third_party:BUILD.third_party",
    sha256 = "4cf0df69731494668bdd6460ed8cb269b68de9c19ad8c27abc24cd72605b2d5b",
    strip_prefix = "json-3.9.1",
    urls = ["https://github.com/nlohmann/json/archive/v3.9.1.tar.gz"],
)

# a local repo representing the third party library locations (e.g. for simavr).
# TODO: this is platform-specific and needs to be generalised.
new_local_repository(
    name = "third_party",
    build_file = "third_party/BUILD.third_party",
    path = "/usr/",
    workspace_file = "third_party/WORKSPACE.third_party",
)
